### PR TITLE
Fix/refactor conflict manager

### LINKED ISSUE #55: Conflict Manager should be refactored to grant plugins more options for tuning
### Descriptive summary
The conflict detector system in Guidance does not allow for plugins to control the parameters such as spatial hash map cell size. This makes it difficult to use the system for purposes other than the original lane change use case it was designed for. The system would better serve users if alternative spatial structures or those with differing dimensions could be injected. To this end IConflictDetector.java and ConflictManager.java could be refactored to support this. In the short term this will directly benefit Traffic Signal Plugin development
### Expected behavior
Conflict detection system in guidance can be used for a variety of collision avoidance use cases
### Actual behavior
The limitations on parameter tuning prevent plugins from modifying the spatial hash map cell size which directly affects collision lookup performance. 
### Steps to reproduce the behavior
N/A

### Related work
N/A
Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by msmcconnell**
Fixes #55  ; refs #54

Addresses Issue 55 by refactoring the conflict manager system in guidance to support dependency injection of different collision checking structure objects. This allows a plugin or other guidance component to use it's own parameters for collision checking while still levering the logic in ConflictManager

Changes proposed in this pull request:
* Create an ISpatialStructureFactory for making different collision checking structures
* Refactor ConflictManager.java to use the ISpatialStructureFactory and ISpatialStructure interface instead of the NSpatialHashMap directly. Different ISpatialStructure objects can then be injected
* Rename spatialhashmap package to spatialstructure package to better reflect its purpose.
* Fix all unit tests based on api changes
* Update toString method in CartesianObject to be more verbose
* Update Traffic Signal Plugin to support this change

@qswawrq

### CODE REVIEW

File: carmajava/geometry/src/main/java/gov/dot/fhwa/saxton/carma/geometry/cartesian/spatialstructure/NSpatialHashMapFactory.java [hunk 1]
```diff
@@ -14,28 +14,29 @@
...
 
 /**
- * Factory/builder pattern class for the construction of NSpatialHashMap instances.
+ * Factory pattern class for the construction of NSpatialHashMap instances.
  * <p>
  * Assigns the strategies needed by the NSpatialHashMap instance.
  */
-public class NSpatialHashMapFactory {
+public class NSpatialHashMapFactory implements ISpatialStructureFactory{
+    public final double[] cellDims;
```
Comment (qswawrq) [inline carmajava/geometry/src/main/java/gov/dot/fhwa/saxton/carma/geometry/cartesian/spatialstructure/NSpatialHashMapFactory.java]: I think the goal for factory pattern is to create different classes with the same interface with one factory. So it should make more sense for me to have buildSpatialStructure taking in the dimension and returning a NSpatialHashMap object.

Comment (msmcconnell) [reply carmajava/geometry/src/main/java/gov/dot/fhwa/saxton/carma/geometry/cartesian/spatialstructure/NSpatialHashMapFactory.java]: The issue is that not every spatial structure would have the same constructor. If we had an octree there wouldn't be a cell size array to pass in. A kdtree would similarly be a different set of parameters.

Comment (msmcconnell) [reply carmajava/geometry/src/main/java/gov/dot/fhwa/saxton/carma/geometry/cartesian/spatialstructure/NSpatialHashMapFactory.java]: You are right this isn't pure factory pattern (maybe it qualifies as builder). I want dependency injection of the specific type of spatial structure but I need to be able to create multiple structures, thus the interface for the factory instead of just the object

Comment (qswawrq) [reply carmajava/geometry/src/main/java/gov/dot/fhwa/saxton/carma/geometry/cartesian/spatialstructure/NSpatialHashMapFactory.java]: Got you.
