### PR TITLE
Assign Autoware plugin correct capability tag

### LINKED ISSUE #511: Autoware Plugin does not have correct Capability tag
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Autoware Plugin does not report correct capability tag and thus is missed by the Arbitrator when it queries the plugin manager for plugins supporting the "strategic_plan/plan_maneuvers" capability.

### Expected behavior
Arbitrator locates the Autoware plugin and uses it to generate a maneuver plan.

### Software version this applies to
3.2.0 develop branch at time of issue creation

### Actual behavior
Arbitrator is unable to locate the Autoware plugin and thus fails to generate any maneuver plan at all.

### Steps to reproduce the behavior

1. Run carma start all and observe vehicle behavior. Vehicle will not move and no maneuver plans or trajectories will be generated.

### PR DESCRIPTION
**Pull request by Supraluminal**
Update Autoware plugin capability tag in autoware_plugin.cpp to match the strategic plan capability as defined by the Arbitrator's capability interface in capabilities_interface.cpp:23: "strategic_plan/plan_maneuvers".

This resolves an issue whereby the Arbitrator wasn't able to find any plugins to query to generate strategic plans. Closes #511.

# PR Details
## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: autoware_plugin/src/autoware_plugin.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ namespace autoware_plugin
         plugin_discovery_msg_.available = true;
         plugin_discovery_msg_.activated = false;
         plugin_discovery_msg_.type = cav_msgs::Plugin::STRATEGIC;
-        plugin_discovery_msg_.capability = "waypoint_following/autoware";
```
Comment (qswawrq) [inline autoware_plugin/src/autoware_plugin.cpp]: Emm... I am not sure that is a actual defect.The capability here is described as "top-level-feature/implementation" instead of an actual service name. The service name is composed by health_monitor using its config.yaml file.
```# String: Plugin service name prefix
plugin_service_prefix: /guidance/plugin/

# String: Strategic plugin service suffix
strategic_plugin_service_suffix: /plan_maneuver

# String: Tactical plugin service suffix
tactical_plugin_service_suffix: /plan_trajectory
