### PR TITLE
Route Following Plugin

### LINKED ISSUE #559: Build Route Following Strategic Plugin
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
To utilize lanelet2 route and replace autoware_plugin, we need to build a route following feature. The top level strategic plugin is called route following plugin. The current implementation only supports lane keeping functionality and will log a warning when a lane-change maneuver is required on the route.
### Expected behavior
N/A
### Software version this applies to

3.2.0
### Actual behavior
N/A
### Steps to reproduce the behavior
N/A

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by qswawrq**
# PR Details
## Description
To resolve #559, this is the initial implementation of route following plugin.

## Related Issue
#559 

## Motivation and Context
Adding a new feature.

## How Has This Been Tested?
All unit tests passed.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: route_following_plugin/include/route_following_plugin.h [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+namespace route_following_plugin
+{
+
+    class RouteFollowingPlugin
+    {
+
+    public:
+
+        // constant speed limit for test
+        // TODO Once world_model and vector map is ready, it should be removed
```
Comment (Supraluminal) [inline route_following_plugin/include/route_following_plugin.h]: We might want to think about whether this data will be available by the time this integration branch gets merged into develop. I think this world model and vector map data is a requirement for the tactical plugin to work, and thus we'll need that to function before we can merge this. Since the interface is already there, is it possible to start using the speed limits from that in this strategic plugin?

File: route_following_plugin/package.xml [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+ WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ License for the specific language governing permissions and limitations under
+ the License.
+-->
+
+<package format="2">
+  <name>route_following_plugin</name>
+  <version>3.2.0</version>
+  <description>The strategic plugin generates maneuvers to make the vehicle follow the route. </description>
+  <maintainer email="carma@todo.todo">carma</maintainer>
```
Comment (Supraluminal) [inline route_following_plugin/package.xml]: I'd update both of these emails to `carma@dot.gov` now that we have that email operational.

File: route_following_plugin/src/route_following_plugin.cpp [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+{
+    RouteFollowingPlugin::RouteFollowingPlugin() : mvr_duration_(16.0), current_speed_(0.0) { }
+
+    void RouteFollowingPlugin::initialize()
+    {
+        
+        nh_.reset(new ros::CARMANodeHandle());
+        pnh_.reset(new ros::CARMANodeHandle("~"));
+        
+        plan_maneuver_srv_ = nh_->advertiseService("plugins/RouteFollowingPlugin/plan_maneuvers", &RouteFollowingPlugin::plan_maneuver_cb, this);
```
Comment (Supraluminal) [inline route_following_plugin/src/route_following_plugin.cpp]: Should this just advertise `strategic_plan/plan_maneuvers` or `~/strategic_plan/plan_maneuvers` (I can never recall which one is which) so that it can be remapped in the launch file to the appropriate place?

File: route_following_plugin/src/route_following_plugin.cpp [hunk 4]
```diff
@@ -0,0 +1,176 @@
...
+        
+        pnh_->param<double>("minimal_maneuver_duration", mvr_duration_, 16.0);
+
+        wml_.reset(new carma_wm::WMListener());
+        // set world model point form wm listener
+        wm_ = wml_->getWorldModel();
+
+        ros::CARMANodeHandle::setSpinCallback([this]()
+        {
+            plugin_discovery_pub_.publish(plugin_discovery_msg_);
```
Comment (Supraluminal) [inline route_following_plugin/src/route_following_plugin.cpp]: Is publishing this discovery message with `activated = false` every timestep going to cause issues? If the user activates it from the UI, would publishing this message with `activated = false` deactivate it with the plugin manager?

File: route_following_plugin/src/route_following_plugin.cpp [hunk 5]
```diff
@@ -0,0 +1,176 @@
...
+        }
+        auto current_lanelet = current_lanelets[0];
+        auto shortest_path = wm_->getRoute()->shortestPath();
+        double current_progress = wm_->routeTrackPos(current_loc).downtrack;
+        double speed_progress = current_speed_;
+        double total_maneuver_length = current_progress + mvr_duration_ * RouteFollowingPlugin::TWENTY_FIVE_MPH_IN_MS;
+        int last_lanelet_index = findLaneletIndexFromPath(current_lanelet.second.id(), shortest_path);
+        if(last_lanelet_index == -1)
+        {
+            ROS_WARN_STREAM("Cannot find current lanelet in shortest path!");
```
Comment (Supraluminal) [inline route_following_plugin/src/route_following_plugin.cpp]: This is the case where we'd expect `RouteManager` or someone else to throw a left route error, correct? Just making sure I understand.

File: route_following_plugin/src/route_following_plugin.cpp [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+        {
+            if(path[i].id() == target_id)
+            {
+                return i;
+            }
+        }
+        return -1;
+    }
+
+    cav_msgs::Maneuver RouteFollowingPlugin::composeManeuverMessage(double current_dist, double end_dist, double current_speed, int lane_id, ros::Time current_time)
```
Comment (Supraluminal) [inline route_following_plugin/src/route_following_plugin.cpp]: Assuming we can eventually get the speed limits (or other target speed) from the World Model, you'd need to parameterize this method for target speed too, correct? Might be a better idea to add target speed as a parameter here, and then if we do need to use the placeholder `RouteFollowingPlugin::TWENTY_FIVE_MPH_IN_MS` value for now we can do that wherever we'd be invoking this method.

File: route_following_plugin/include/route_following_plugin.h (hunk 1 above)
Comment (qswawrq) [reply route_following_plugin/include/route_following_plugin.h]: On one hand, there is no interface in the world_model to expose traffic rule. I believe it is still in progress. One the other hand, I am not sure if Samir finished his task on adding speed limit into vector map. Those two things are what I am waiting on. I agree it should not be merged into develop before we have those. Right now it targets to the routing integration branch.

File: route_following_plugin/src/route_following_plugin.cpp (hunk 3 above)
Comment (qswawrq) [reply route_following_plugin/src/route_following_plugin.cpp]: Sure.

File: route_following_plugin/package.xml (hunk 2 above)
Comment (qswawrq) [reply route_following_plugin/package.xml]: Sure.

File: route_following_plugin/src/route_following_plugin.cpp (hunk 4 above)
Comment (qswawrq) [reply route_following_plugin/src/route_following_plugin.cpp]: I do not think so. Health Manager only updates a plugin's activity based on user selection (service call from UI). This field will be ignored.

File: route_following_plugin/src/route_following_plugin.cpp (hunk 5 above)
Comment (qswawrq) [reply route_following_plugin/src/route_following_plugin.cpp]: If we stay on the route, it will not be trigger. Otherwise, we expect route manager to flag left_route first.

File: route_following_plugin/src/route_following_plugin.cpp (hunk 6 above)
Comment (qswawrq) [reply route_following_plugin/src/route_following_plugin.cpp]: Sure. Make sense to me.

**Comment by qswawrq** [comment]
Last commit should address all your comments.

File: route_following_plugin/include/route_following_plugin.h (hunk 1 above)
Comment (Supraluminal) [reply route_following_plugin/include/route_following_plugin.h]: I'm not sure if we have a separate story for integrating that, or how the best way to track that is then. I just want to make sure we don't lose track of that somewhere as we'll really need to use that functionality once that data is available. Do you think that fits within the scope of another story, I don't want to hold this one open for a single issue if that's avoidable.

Comment (qswawrq) [reply route_following_plugin/include/route_following_plugin.h]: Does it make sense to do it under that wrap-all integration test? We probably are ready at that time.

**Comment by Supraluminal** [comment]
We'll plan to create a new story to implement the speed limit integration with the CARMA world model once that data is exposed, for now we can close out this PR and story.
