### PR TITLE
Bugfix/arbitrator planning rate

### LINKED ISSUE #451: Arbitrator node publishes maneuver plan every 10 seconds
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Arbitrator node publishes maneuver plan every 10 seconds in guidance ENGAGE state, which is significantly lower than expect. It also causes the plan delegator deems some maneuver plan as expired (because the end time of the plan is later than the current time).
### Expected behavior
Arbitrator node publishes maneuver plan at 1 Hz after entering planning state.
### Software version this applies to

3.1.0
### Actual behavior
Arbitrator node publishes maneuver plan every 10 seconds in guidance ENGAGE state.
### Steps to reproduce the behavior
Launch CARMAPlatform in docker and use rostopic hz on "guidance/final_maneuver_plan" topic.
### Related work
N/A
Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by Supraluminal**
# PR Details
## Related Issue

Fixes #451 

## Motivation and Context

As per issue #451 the Arbitrator <--> Autoware Plugin interaction was not occurring at the correct frequency (1hz) and was instead occuring at a much lower (0.1hz) frequency. This issue was the result of a confluence of factors:

1. Arbitrator internal timing loop configuration caused it to loop far tighter than anticipated, even though service calls were failing. This issue was masked by the two other factors.
2. A comparison of plan duration ended up comparing two doubles that were supposed to be the same (`ros::Duration(15)` vs the duration of a plan from `ros::Time::now()` to `ros::Time::now() + ros::Duration(15)` but depending on the value of ros::Time::now(), this comparison failed several times before it passed.
3. Plugin discovery was not clearing already discovered plugins from the records when it received new plugin data, thus effectively registering a plugin multiple times and causing extra services calls.

## How Has This Been Tested?

Tested locally via an integration test with the `Arbitrator`, `Health Monitor`, and `Autoware Plugin` nodes.

```rostopic hz /guidance/final_maneuver_plan
subscribed to [/guidance/final_maneuver_plan]
no new messages
no new messages
average rate: 0.953
	min: 1.049s max: 1.049s std dev: 0.00000s window: 2
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00057s window: 3
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00056s window: 4
average rate: 0.953
	min: 1.049s max: 1.051s std dev: 0.00076s window: 5
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00070s window: 6
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00064s window: 7
average rate: 0.953
	min: 1.049s max: 1.051s std dev: 0.00062s window: 8
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00073s window: 9
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00070s window: 10
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00067s window: 11
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00070s window: 12
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00069s window: 13
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00071s window: 14
average rate: 0.952
	min: 1.049s max: 1.051s std dev: 0.00070s window: 15
```

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: arbitrator/src/arbitrator.cpp [hunk 1]
```diff
@@ -94,23 +103,33 @@ namespace arbitrator
...
+        else
         {
-            ROS_INFO_STREAM("Arbitrator is publishing plan " << plan.maneuver_plan_id << " of duration " << plan_duration << " as current maneuver plan");
+            ROS_WARN("Arbitrator was unable to generate a plan!");
         }
-        final_plan_pub_.publish(plan);
 
         next_planning_process_start_ = planning_process_start + time_between_plans_;
+
+        sm_->submit_event(ArbitratorEvent::PLANNING_COMPLETE);
```
Comment (qswawrq) [inline arbitrator/src/arbitrator.cpp]: What happens after you submit this PLANNING_COMPLETE event? I do not think we want state machine to transit to another state?

Comment (Supraluminal) [reply arbitrator/src/arbitrator.cpp]: After we submit `PLANNING_COMPLETE` the state machine transitions to `WAITING` state, where it stays for the remainder of the time until the next planning cycle. It'll sleep for that much time, the transition back to `PLANNING` state.

Comment (qswawrq) [reply arbitrator/src/arbitrator.cpp]: Cool!
